2014-10-25 06:58:50,800 - [INFO] - from play in pool-31-thread-2 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

2014-10-25 06:58:54,162 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 06:58:54,581 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 06:58:55,852 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-10-25 06:59:22,526 - [ERROR] - from play in play-internal-execution-context-1 
Cannot invoke the action, eventually got an error: java.lang.NumberFormatException: For input string: "4761113682622"

2014-10-25 06:59:22,560 - [ERROR] - from application in play-internal-execution-context-1 


! @6k1od95k5 - Internal server error, for (GET) [/submitRating/food/1/4] ->

play.api.Application$$anon$1: Execution exception[[NumberFormatException: For input string: "4761113682622"]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NumberFormatException: For input string: "4761113682622"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_20]
	at java.lang.Integer.parseInt(Integer.java:583) ~[na:1.8.0_20]
	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_20]
	at controllers.UserFeed.UserFeedOnRestaurant.feedOnFood(UserFeedOnRestaurant.java:59) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$22$$anonfun$apply$22.apply(routes_routing.scala:301) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$22$$anonfun$apply$22.apply(routes_routing.scala:301) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 06:59:28,298 - [ERROR] - from play in play-internal-execution-context-1 
Cannot invoke the action, eventually got an error: java.lang.NumberFormatException: For input string: "4761113682622"

2014-10-25 06:59:28,304 - [ERROR] - from application in play-internal-execution-context-1 


! @6k1od9e79 - Internal server error, for (GET) [/submitRating/food/1/4] ->

play.api.Application$$anon$1: Execution exception[[NumberFormatException: For input string: "4761113682622"]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NumberFormatException: For input string: "4761113682622"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_20]
	at java.lang.Integer.parseInt(Integer.java:583) ~[na:1.8.0_20]
	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_20]
	at controllers.UserFeed.UserFeedOnRestaurant.feedOnFood(UserFeedOnRestaurant.java:59) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$22$$anonfun$apply$22.apply(routes_routing.scala:301) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$22$$anonfun$apply$22.apply(routes_routing.scala:301) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 06:59:57,122 - [ERROR] - from play in play-internal-execution-context-1 
Cannot invoke the action, eventually got an error: java.lang.NumberFormatException: For input string: "4761113682622"

2014-10-25 06:59:57,126 - [ERROR] - from application in play-internal-execution-context-1 


! @6k1odb4nn - Internal server error, for (GET) [/submitRating/food/1/4] ->

play.api.Application$$anon$1: Execution exception[[NumberFormatException: For input string: "4761113682622"]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NumberFormatException: For input string: "4761113682622"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_20]
	at java.lang.Integer.parseInt(Integer.java:583) ~[na:1.8.0_20]
	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_20]
	at controllers.UserFeed.UserFeedOnRestaurant.feedOnFood(UserFeedOnRestaurant.java:59) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$22$$anonfun$apply$22.apply(routes_routing.scala:301) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$22$$anonfun$apply$22.apply(routes_routing.scala:301) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 07:00:08,327 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 07:00:08,386 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 07:00:08,459 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-10-25 07:08:46,288 - [INFO] - from play in play-internal-execution-context-1 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 07:08:46,341 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 07:08:46,423 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-10-25 07:10:34,805 - [INFO] - from play in play-internal-execution-context-2 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 07:10:34,856 - [INFO] - from play in play-internal-execution-context-2 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 07:10:34,936 - [INFO] - from play in play-internal-execution-context-2 
Application started (Dev)

2014-10-25 07:17:54,908 - [INFO] - from play in play-internal-execution-context-2 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 07:17:54,950 - [INFO] - from play in play-internal-execution-context-2 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 07:17:55,034 - [INFO] - from play in play-internal-execution-context-2 
Application started (Dev)

2014-10-25 07:22:30,053 - [INFO] - from play in play-internal-execution-context-3 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 07:22:30,118 - [INFO] - from play in play-internal-execution-context-3 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 07:22:30,207 - [INFO] - from play in play-internal-execution-context-3 
Application started (Dev)

2014-10-25 07:23:46,526 - [INFO] - from play in play-internal-execution-context-4 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 07:23:46,565 - [INFO] - from play in play-internal-execution-context-4 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 07:23:46,657 - [INFO] - from play in play-internal-execution-context-4 
Application started (Dev)

2014-10-25 07:33:29,675 - [INFO] - from play in play-internal-execution-context-4 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 07:33:29,719 - [INFO] - from play in play-internal-execution-context-4 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 07:33:29,798 - [INFO] - from play in play-internal-execution-context-4 
Application started (Dev)

2014-10-25 07:39:19,684 - [INFO] - from play in play-internal-execution-context-4 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 07:39:19,740 - [INFO] - from play in play-internal-execution-context-4 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 07:39:19,827 - [INFO] - from play in play-internal-execution-context-4 
Application started (Dev)

2014-10-25 07:44:32,007 - [INFO] - from play in play-internal-execution-context-5 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 07:44:32,044 - [INFO] - from play in play-internal-execution-context-5 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 07:44:32,130 - [INFO] - from play in play-internal-execution-context-5 
Application started (Dev)

2014-10-25 07:44:40,748 - [ERROR] - from play in play-internal-execution-context-5 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: ERROR executing DML bindLog[] error['Infinity' is not a valid numeric or approximate numeric value]

2014-10-25 07:44:40,753 - [ERROR] - from application in play-internal-execution-context-5 


! @6k1oj7mk8 - Internal server error, for (GET) [/submitRating/restaurant/1/5] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: ERROR executing DML bindLog[] error['Infinity' is not a valid numeric or approximate numeric value]]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: javax.persistence.PersistenceException: ERROR executing DML bindLog[] error['Infinity' is not a valid numeric or approximate numeric value]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:97) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:66) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:82) ~[na:na]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:452) ~[na:na]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:478) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:365) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.forceUpdate(DefaultPersister.java:176) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1609) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1598) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1575) ~[na:na]
	at com.avaje.ebean.Ebean.update(Ebean.java:496) ~[na:na]
	at play.db.ebean.Model.update(Model.java:133) ~[na:na]
	at controllers.UserFeed.UserFeedOnRestaurant.feedOnRestaurant(UserFeedOnRestaurant.java:44) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$21$$anonfun$apply$21.apply(routes_routing.scala:293) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$21$$anonfun$apply$21.apply(routes_routing.scala:293) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted
Caused by: java.sql.SQLException: 'Infinity' is not a valid numeric or approximate numeric value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078) ~[na:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989) ~[na:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975) ~[na:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920) ~[na:na]
	at com.mysql.jdbc.PreparedStatement.setDouble(PreparedStatement.java:3740) ~[na:na]
	at com.jolbox.bonecp.PreparedStatementHandle.setDouble(PreparedStatementHandle.java:788) ~[na:na]
	at com.avaje.ebeaninternal.server.type.DataBind.setDouble(DataBind.java:83) ~[na:na]
	at com.avaje.ebeaninternal.server.type.ScalarTypeDouble.bind(ScalarTypeDouble.java:24) ~[na:na]
	at com.avaje.ebeaninternal.server.type.ScalarTypeDouble.bind(ScalarTypeDouble.java:14) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.bind(BeanProperty.java:631) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bindInternal(DmlHandler.java:240) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bind(DmlHandler.java:199) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableProperty.dmlBind(BindableProperty.java:81) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableProperty.dmlBind(BindableProperty.java:63) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableList.dmlBind(BindableList.java:56) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.UpdatePlan.bindSet(UpdatePlan.java:91) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.UpdateMeta.bind(UpdateMeta.java:77) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.UpdateHandler.bind(UpdateHandler.java:60) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:79) ~[na:na]
	... 33 common frames omitted

2014-10-25 07:44:50,896 - [ERROR] - from play in play-internal-execution-context-5 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: ERROR executing DML bindLog[] error['NaN' is not a valid numeric or approximate numeric value]

2014-10-25 07:44:50,900 - [ERROR] - from application in play-internal-execution-context-5 


! @6k1oj8bkf - Internal server error, for (GET) [/submitRating/restaurant/1/5] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: ERROR executing DML bindLog[] error['NaN' is not a valid numeric or approximate numeric value]]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: javax.persistence.PersistenceException: ERROR executing DML bindLog[] error['NaN' is not a valid numeric or approximate numeric value]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:97) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:66) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:82) ~[na:na]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:452) ~[na:na]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:478) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:365) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.forceUpdate(DefaultPersister.java:176) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1609) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1598) ~[na:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1575) ~[na:na]
	at com.avaje.ebean.Ebean.update(Ebean.java:496) ~[na:na]
	at play.db.ebean.Model.update(Model.java:133) ~[na:na]
	at controllers.UserFeed.UserFeedOnRestaurant.feedOnRestaurant(UserFeedOnRestaurant.java:44) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$21$$anonfun$apply$21.apply(routes_routing.scala:293) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$21$$anonfun$apply$21.apply(routes_routing.scala:293) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted
Caused by: java.sql.SQLException: 'NaN' is not a valid numeric or approximate numeric value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078) ~[na:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:989) ~[na:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:975) ~[na:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:920) ~[na:na]
	at com.mysql.jdbc.PreparedStatement.setDouble(PreparedStatement.java:3740) ~[na:na]
	at com.jolbox.bonecp.PreparedStatementHandle.setDouble(PreparedStatementHandle.java:788) ~[na:na]
	at com.avaje.ebeaninternal.server.type.DataBind.setDouble(DataBind.java:83) ~[na:na]
	at com.avaje.ebeaninternal.server.type.ScalarTypeDouble.bind(ScalarTypeDouble.java:24) ~[na:na]
	at com.avaje.ebeaninternal.server.type.ScalarTypeDouble.bind(ScalarTypeDouble.java:14) ~[na:na]
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.bind(BeanProperty.java:631) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bindInternal(DmlHandler.java:240) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bind(DmlHandler.java:199) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableProperty.dmlBind(BindableProperty.java:81) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableProperty.dmlBind(BindableProperty.java:63) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableList.dmlBind(BindableList.java:56) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.UpdatePlan.bindSet(UpdatePlan.java:91) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.UpdateMeta.bind(UpdateMeta.java:77) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.UpdateHandler.bind(UpdateHandler.java:60) ~[na:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:79) ~[na:na]
	... 33 common frames omitted

2014-10-25 07:56:50,562 - [INFO] - from play in play-internal-execution-context-5 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 07:56:50,596 - [INFO] - from play in play-internal-execution-context-5 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 07:56:50,661 - [INFO] - from play in play-internal-execution-context-5 
Application started (Dev)

2014-10-25 08:00:44,825 - [INFO] - from play in play-internal-execution-context-5 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 08:00:44,861 - [INFO] - from play in play-internal-execution-context-5 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 08:00:44,927 - [INFO] - from play in play-internal-execution-context-5 
Application started (Dev)

2014-10-25 08:01:21,273 - [INFO] - from play in play-internal-execution-context-5 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 08:01:21,306 - [INFO] - from play in play-internal-execution-context-5 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 08:01:21,790 - [INFO] - from play in play-internal-execution-context-5 
Application started (Dev)

2014-10-25 08:07:00,569 - [INFO] - from play in play-internal-execution-context-9 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 08:07:00,603 - [INFO] - from play in play-internal-execution-context-9 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 08:07:00,664 - [INFO] - from play in play-internal-execution-context-9 
Application started (Dev)

2014-10-25 08:08:12,076 - [INFO] - from play in play-internal-execution-context-10 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 08:08:12,111 - [INFO] - from play in play-internal-execution-context-10 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 08:08:12,174 - [INFO] - from play in play-internal-execution-context-10 
Application started (Dev)

2014-10-25 08:19:15,250 - [INFO] - from play in play-internal-execution-context-11 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 08:19:15,324 - [INFO] - from play in play-internal-execution-context-11 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 08:19:15,416 - [INFO] - from play in play-internal-execution-context-11 
Application started (Dev)

2014-10-25 08:21:55,432 - [INFO] - from play in play-internal-execution-context-12 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 08:21:55,468 - [INFO] - from play in play-internal-execution-context-12 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 08:21:55,538 - [INFO] - from play in play-internal-execution-context-12 
Application started (Dev)

2014-10-25 08:25:27,223 - [INFO] - from play in play-internal-execution-context-12 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 08:25:27,257 - [INFO] - from play in play-internal-execution-context-12 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 08:25:27,329 - [INFO] - from play in play-internal-execution-context-12 
Application started (Dev)

2014-10-25 08:38:46,635 - [INFO] - from play in play-internal-execution-context-12 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 08:38:46,663 - [INFO] - from play in play-internal-execution-context-12 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 08:38:46,726 - [INFO] - from play in play-internal-execution-context-12 
Application started (Dev)

2014-10-25 08:44:16,147 - [INFO] - from play in play-internal-execution-context-12 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 08:44:16,181 - [INFO] - from play in play-internal-execution-context-12 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 08:44:16,265 - [INFO] - from play in play-internal-execution-context-12 
Application started (Dev)

2014-10-25 08:44:21,257 - [ERROR] - from play in play-internal-execution-context-12 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 08:44:21,261 - [ERROR] - from application in play-internal-execution-context-12 


! @6k1p13fa4 - Internal server error, for (GET) [/search/ra] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.answer(AnswerQueryWithJson.java:53) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$16$$anonfun$apply$16.apply(routes_routing.scala:253) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$16$$anonfun$apply$16.apply(routes_routing.scala:253) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 08:44:22,379 - [ERROR] - from play in play-internal-execution-context-12 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 08:44:22,382 - [ERROR] - from application in play-internal-execution-context-12 


! @6k1p13h17 - Internal server error, for (GET) [/search/r] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.answer(AnswerQueryWithJson.java:53) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$16$$anonfun$apply$16.apply(routes_routing.scala:253) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$16$$anonfun$apply$16.apply(routes_routing.scala:253) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 08:44:23,831 - [ERROR] - from play in play-internal-execution-context-12 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 08:44:23,834 - [ERROR] - from application in play-internal-execution-context-12 


! @6k1p13j54 - Internal server error, for (GET) [/search/R] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.answer(AnswerQueryWithJson.java:53) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$16$$anonfun$apply$16.apply(routes_routing.scala:253) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$16$$anonfun$apply$16.apply(routes_routing.scala:253) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 08:44:40,972 - [INFO] - from play in play-internal-execution-context-12 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 08:44:41,007 - [INFO] - from play in play-internal-execution-context-12 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 08:44:41,075 - [INFO] - from play in play-internal-execution-context-12 
Application started (Dev)

2014-10-25 08:46:24,623 - [INFO] - from play in play-internal-execution-context-12 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 08:46:24,654 - [INFO] - from play in play-internal-execution-context-12 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 08:46:24,741 - [INFO] - from play in play-internal-execution-context-12 
Application started (Dev)

2014-10-25 09:04:38,568 - [INFO] - from play in play-internal-execution-context-14 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:04:38,607 - [INFO] - from play in play-internal-execution-context-14 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:04:38,723 - [INFO] - from play in play-internal-execution-context-14 
Application started (Dev)

2014-10-25 09:04:38,955 - [INFO] - from play in play-internal-execution-context-14 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:04:38,988 - [INFO] - from play in play-internal-execution-context-14 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:04:39,066 - [INFO] - from play in play-internal-execution-context-14 
Application started (Dev)

2014-10-25 09:04:49,688 - [ERROR] - from play in play-internal-execution-context-15 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 09:04:49,700 - [ERROR] - from application in play-internal-execution-context-15 


! @6k1p3lcfg - Internal server error, for (POST) [/answer] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.searchPage(AnswerQueryWithJson.java:100) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 09:16:46,354 - [INFO] - from play in play-internal-execution-context-15 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:16:46,390 - [INFO] - from play in play-internal-execution-context-15 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:16:46,462 - [INFO] - from play in play-internal-execution-context-15 
Application started (Dev)

2014-10-25 09:17:09,150 - [INFO] - from play in play-internal-execution-context-16 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:17:09,181 - [INFO] - from play in play-internal-execution-context-16 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:17:09,266 - [INFO] - from play in play-internal-execution-context-16 
Application started (Dev)

2014-10-25 09:17:15,452 - [ERROR] - from play in play-internal-execution-context-16 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 09:17:15,455 - [ERROR] - from application in play-internal-execution-context-16 


! @6k1p5bnkj - Internal server error, for (POST) [/answer] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.searchPage(AnswerQueryWithJson.java:100) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 09:18:35,313 - [INFO] - from play in play-internal-execution-context-16 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:18:35,347 - [INFO] - from play in play-internal-execution-context-16 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:18:35,409 - [INFO] - from play in play-internal-execution-context-16 
Application started (Dev)

2014-10-25 09:18:35,421 - [ERROR] - from play in play-internal-execution-context-16 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 09:18:35,426 - [ERROR] - from application in play-internal-execution-context-16 


! @6k1p5gc2d - Internal server error, for (POST) [/answer] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.searchPage(AnswerQueryWithJson.java:100) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 09:20:40,213 - [INFO] - from play in play-internal-execution-context-17 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:20:40,247 - [INFO] - from play in play-internal-execution-context-17 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:20:40,318 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2014-10-25 09:22:10,320 - [INFO] - from play in play-internal-execution-context-17 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:22:10,347 - [INFO] - from play in play-internal-execution-context-17 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:22:10,413 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2014-10-25 09:24:03,021 - [INFO] - from play in play-internal-execution-context-17 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:24:03,061 - [INFO] - from play in play-internal-execution-context-17 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:24:03,147 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2014-10-25 09:24:23,215 - [INFO] - from play in play-internal-execution-context-17 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:24:23,245 - [INFO] - from play in play-internal-execution-context-17 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:24:23,322 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2014-10-25 09:25:04,678 - [INFO] - from play in play-internal-execution-context-17 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:25:04,711 - [INFO] - from play in play-internal-execution-context-17 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:25:04,801 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2014-10-25 09:25:41,834 - [INFO] - from play in play-internal-execution-context-17 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:25:41,866 - [INFO] - from play in play-internal-execution-context-17 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:25:41,940 - [INFO] - from play in play-internal-execution-context-17 
Application started (Dev)

2014-10-25 09:33:19,876 - [INFO] - from play in play-internal-execution-context-19 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:33:19,909 - [INFO] - from play in play-internal-execution-context-19 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:33:19,987 - [INFO] - from play in play-internal-execution-context-19 
Application started (Dev)

2014-10-25 09:35:57,753 - [INFO] - from play in play-internal-execution-context-19 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:35:57,795 - [INFO] - from play in play-internal-execution-context-19 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:35:57,912 - [INFO] - from play in play-internal-execution-context-19 
Application started (Dev)

2014-10-25 09:36:39,935 - [INFO] - from play in play-internal-execution-context-19 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:36:39,960 - [INFO] - from play in play-internal-execution-context-19 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:36:40,041 - [INFO] - from play in play-internal-execution-context-19 
Application started (Dev)

2014-10-25 09:39:28,892 - [INFO] - from play in play-internal-execution-context-21 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:39:28,927 - [INFO] - from play in play-internal-execution-context-21 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:39:29,011 - [INFO] - from play in play-internal-execution-context-21 
Application started (Dev)

2014-10-25 09:39:29,384 - [INFO] - from play in play-internal-execution-context-21 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:39:29,415 - [INFO] - from play in play-internal-execution-context-21 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:39:29,481 - [INFO] - from play in play-internal-execution-context-21 
Application started (Dev)

2014-10-25 09:40:18,653 - [INFO] - from play in play-internal-execution-context-21 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:40:18,687 - [INFO] - from play in play-internal-execution-context-21 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:40:18,765 - [INFO] - from play in play-internal-execution-context-21 
Application started (Dev)

2014-10-25 09:41:56,569 - [INFO] - from play in play-internal-execution-context-23 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:41:56,602 - [INFO] - from play in play-internal-execution-context-23 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:41:56,731 - [INFO] - from play in play-internal-execution-context-23 
Application started (Dev)

2014-10-25 09:43:24,234 - [INFO] - from play in play-internal-execution-context-23 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:43:24,269 - [INFO] - from play in play-internal-execution-context-23 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:43:24,369 - [INFO] - from play in play-internal-execution-context-23 
Application started (Dev)

2014-10-25 09:43:50,710 - [ERROR] - from play in play-internal-execution-context-23 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 09:43:50,713 - [ERROR] - from application in play-internal-execution-context-23 


! @6k1p8ohgk - Internal server error, for (GET) [/srs/preload] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.preload(AnswerQueryWithJson.java:77) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$15$$anonfun$apply$15.apply(routes_routing.scala:249) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$15$$anonfun$apply$15.apply(routes_routing.scala:249) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 09:45:59,429 - [INFO] - from play in play-internal-execution-context-23 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:45:59,453 - [INFO] - from play in play-internal-execution-context-23 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:45:59,520 - [INFO] - from play in play-internal-execution-context-23 
Application started (Dev)

2014-10-25 09:46:46,285 - [INFO] - from play in play-internal-execution-context-23 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:46:46,323 - [INFO] - from play in play-internal-execution-context-23 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:46:46,404 - [INFO] - from play in play-internal-execution-context-23 
Application started (Dev)

2014-10-25 09:47:47,279 - [INFO] - from play in play-internal-execution-context-26 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:47:47,308 - [INFO] - from play in play-internal-execution-context-26 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:47:47,372 - [INFO] - from play in play-internal-execution-context-26 
Application started (Dev)

2014-10-25 09:49:11,216 - [INFO] - from play in play-internal-execution-context-26 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:49:11,246 - [INFO] - from play in play-internal-execution-context-26 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:49:11,308 - [INFO] - from play in play-internal-execution-context-26 
Application started (Dev)

2014-10-25 09:49:47,403 - [INFO] - from play in play-internal-execution-context-27 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:49:47,435 - [INFO] - from play in play-internal-execution-context-27 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:49:47,507 - [INFO] - from play in play-internal-execution-context-27 
Application started (Dev)

2014-10-25 09:51:38,178 - [INFO] - from play in play-internal-execution-context-28 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 09:51:38,211 - [INFO] - from play in play-internal-execution-context-28 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 09:51:38,295 - [INFO] - from play in play-internal-execution-context-28 
Application started (Dev)

2014-10-25 10:02:31,791 - [INFO] - from play in play-internal-execution-context-28 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:02:31,844 - [INFO] - from play in play-internal-execution-context-28 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:02:31,911 - [INFO] - from play in play-internal-execution-context-28 
Application started (Dev)

2014-10-25 10:05:39,181 - [INFO] - from play in play-internal-execution-context-29 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:05:39,223 - [INFO] - from play in play-internal-execution-context-29 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:05:39,316 - [INFO] - from play in play-internal-execution-context-29 
Application started (Dev)

2014-10-25 10:05:39,727 - [INFO] - from play in play-internal-execution-context-29 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:05:39,758 - [INFO] - from play in play-internal-execution-context-29 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:05:39,821 - [INFO] - from play in play-internal-execution-context-29 
Application started (Dev)

2014-10-25 10:07:24,075 - [INFO] - from play in play-internal-execution-context-30 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:07:24,105 - [INFO] - from play in play-internal-execution-context-30 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:07:24,174 - [INFO] - from play in play-internal-execution-context-30 
Application started (Dev)

2014-10-25 10:07:24,185 - [ERROR] - from play in play-internal-execution-context-31 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 10:07:24,190 - [ERROR] - from application in play-internal-execution-context-31 


! @6k1pc12f6 - Internal server error, for (POST) [/answer] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.searchPage(AnswerQueryWithJson.java:99) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 10:08:40,994 - [INFO] - from play in play-internal-execution-context-31 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:08:41,018 - [INFO] - from play in play-internal-execution-context-31 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:08:41,088 - [INFO] - from play in play-internal-execution-context-31 
Application started (Dev)

2014-10-25 10:08:41,097 - [ERROR] - from play in play-internal-execution-context-31 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 10:08:41,102 - [ERROR] - from application in play-internal-execution-context-31 


! @6k1pc5c9a - Internal server error, for (POST) [/answer] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.searchPage(AnswerQueryWithJson.java:99) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 10:08:51,476 - [ERROR] - from play in play-internal-execution-context-33 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 10:08:51,480 - [ERROR] - from application in play-internal-execution-context-33 


! @6k1pc61ig - Internal server error, for (POST) [/answer] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.searchPage(AnswerQueryWithJson.java:99) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 10:09:03,171 - [ERROR] - from play in play-internal-execution-context-32 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 10:09:03,173 - [ERROR] - from application in play-internal-execution-context-32 


! @6k1pc6j09 - Internal server error, for (POST) [/answer] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.searchPage(AnswerQueryWithJson.java:99) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 10:09:44,967 - [INFO] - from play in play-internal-execution-context-32 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:09:44,987 - [INFO] - from play in play-internal-execution-context-32 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:09:45,042 - [INFO] - from play in play-internal-execution-context-32 
Application started (Dev)

2014-10-25 10:09:48,135 - [ERROR] - from play in play-internal-execution-context-32 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 10:09:48,137 - [ERROR] - from application in play-internal-execution-context-32 


! @6k1pc97dj - Internal server error, for (POST) [/answer] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.searchPage(AnswerQueryWithJson.java:99) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 10:10:37,930 - [INFO] - from play in play-internal-execution-context-34 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:10:37,954 - [INFO] - from play in play-internal-execution-context-34 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:10:38,010 - [INFO] - from play in play-internal-execution-context-34 
Application started (Dev)

2014-10-25 10:10:38,018 - [ERROR] - from play in play-internal-execution-context-34 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 10:10:38,022 - [ERROR] - from application in play-internal-execution-context-34 


! @6k1pcc389 - Internal server error, for (POST) [/answer] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.searchPage(AnswerQueryWithJson.java:99) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 10:10:48,260 - [ERROR] - from play in play-internal-execution-context-34 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 10:10:48,262 - [ERROR] - from application in play-internal-execution-context-34 


! @6k1pccic6 - Internal server error, for (POST) [/answer] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.searchPage(AnswerQueryWithJson.java:99) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 10:10:50,963 - [ERROR] - from play in play-internal-execution-context-34 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2014-10-25 10:10:50,965 - [ERROR] - from application in play-internal-execution-context-34 


! @6k1pccmc5 - Internal server error, for (POST) [/answer] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.NullPointerException: null
	at controllers.Search.AnswerQueryWithJson.searchPage(AnswerQueryWithJson.java:99) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[na:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[na:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 10:11:45,045 - [INFO] - from play in play-internal-execution-context-34 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:11:45,069 - [INFO] - from play in play-internal-execution-context-34 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:11:45,127 - [INFO] - from play in play-internal-execution-context-34 
Application started (Dev)

2014-10-25 10:12:06,273 - [INFO] - from play in play-internal-execution-context-34 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:12:06,303 - [INFO] - from play in play-internal-execution-context-34 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:12:06,368 - [INFO] - from play in play-internal-execution-context-34 
Application started (Dev)

2014-10-25 10:12:48,929 - [INFO] - from play in play-internal-execution-context-34 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:12:48,964 - [INFO] - from play in play-internal-execution-context-34 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:12:49,032 - [INFO] - from play in play-internal-execution-context-34 
Application started (Dev)

2014-10-25 10:13:10,199 - [INFO] - from play in play-internal-execution-context-36 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:13:10,235 - [INFO] - from play in play-internal-execution-context-36 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:13:10,289 - [INFO] - from play in play-internal-execution-context-36 
Application started (Dev)

2014-10-25 10:13:48,656 - [INFO] - from play in play-internal-execution-context-36 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:13:48,688 - [INFO] - from play in play-internal-execution-context-36 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:13:48,770 - [INFO] - from play in play-internal-execution-context-36 
Application started (Dev)

2014-10-25 10:14:49,193 - [INFO] - from play in play-internal-execution-context-36 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:14:49,215 - [INFO] - from play in play-internal-execution-context-36 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:14:49,275 - [INFO] - from play in play-internal-execution-context-36 
Application started (Dev)

2014-10-25 10:15:56,592 - [INFO] - from play in play-internal-execution-context-36 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:15:56,616 - [INFO] - from play in play-internal-execution-context-36 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:15:56,705 - [INFO] - from play in play-internal-execution-context-36 
Application started (Dev)

2014-10-25 10:16:24,408 - [INFO] - from play in play-internal-execution-context-36 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:16:24,431 - [INFO] - from play in play-internal-execution-context-36 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:16:24,489 - [INFO] - from play in play-internal-execution-context-36 
Application started (Dev)

2014-10-25 10:16:41,885 - [INFO] - from play in play-internal-execution-context-37 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:16:41,915 - [INFO] - from play in play-internal-execution-context-37 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:16:42,000 - [INFO] - from play in play-internal-execution-context-37 
Application started (Dev)

2014-10-25 10:33:17,845 - [ERROR] - from application in New I/O worker #7 


! @6k1pfbcma - Internal server error, for (GET) [/restaurant/1?] ->

play.PlayExceptions$CompilationException: Compilation error[illegal start of simple expression]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[na:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]

2014-10-25 10:33:44,781 - [ERROR] - from application in New I/O worker #7 


! @6k1pfd0j5 - Internal server error, for (GET) [/restaurant/1?] ->

play.PlayExceptions$CompilationException: Compilation error[illegal start of simple expression]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[na:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]

2014-10-25 10:34:43,105 - [ERROR] - from application in New I/O worker #7 


! @6k1pfg90a - Internal server error, for (GET) [/restaurant/1?] ->

play.PlayExceptions$CompilationException: Compilation error[not found: value restauants]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[na:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]

2014-10-25 10:35:02,379 - [INFO] - from play in play-internal-execution-context-38 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:35:02,421 - [INFO] - from play in play-internal-execution-context-38 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:35:02,501 - [INFO] - from play in play-internal-execution-context-38 
Application started (Dev)

2014-10-25 10:35:46,515 - [ERROR] - from application in New I/O worker #8 


! @6k1pfjol5 - Internal server error, for (POST) [/answer] ->

play.PlayExceptions$CompilationException: Compilation error[')' expected but 'for' found.]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[na:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]

2014-10-25 10:36:54,041 - [INFO] - from play in play-internal-execution-context-39 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:36:54,070 - [INFO] - from play in play-internal-execution-context-39 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:36:54,142 - [INFO] - from play in play-internal-execution-context-39 
Application started (Dev)

2014-10-25 10:37:21,953 - [INFO] - from play in play-internal-execution-context-39 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:37:21,983 - [INFO] - from play in play-internal-execution-context-39 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:37:22,052 - [INFO] - from play in play-internal-execution-context-39 
Application started (Dev)

2014-10-25 10:48:13,814 - [INFO] - from play in play-internal-execution-context-39 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:48:13,846 - [INFO] - from play in play-internal-execution-context-39 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:48:13,941 - [INFO] - from play in play-internal-execution-context-39 
Application started (Dev)

2014-10-25 10:51:27,728 - [INFO] - from play in play-internal-execution-context-41 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:51:27,759 - [INFO] - from play in play-internal-execution-context-41 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:51:27,818 - [INFO] - from play in play-internal-execution-context-41 
Application started (Dev)

2014-10-25 10:52:21,696 - [ERROR] - from application in New I/O worker #3 


! @6k1phoep8 - Internal server error, for (GET) [/search/bee] ->

play.PlayExceptions$UnexpectedException: Unexpected exception[The compilation failed without reporting any problem!]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$17.apply(PlayReloader.scala:306) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$17.apply(PlayReloader.scala:306) ~[na:na]
	at scala.Option.getOrElse(Option.scala:120) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:305) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[na:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]
sbt.compiler.CompileFailed: null
	at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:77) ~[na:na]
	at sbt.compiler.JavaTool$class.apply(JavaCompiler.scala:35) ~[na:na]
	at sbt.compiler.JavaCompiler$JavaTool0.apply(JavaCompiler.scala:63) ~[na:na]
	at sbt.compiler.JavaCompiler$class.compile(JavaCompiler.scala:21) ~[na:na]
	at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:63) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply$mcV$sp(AggressiveCompile.scala:126) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:126) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:126) ~[na:na]
	at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:159) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3.compileJava$1(AggressiveCompile.scala:125) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:142) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:86) ~[na:na]
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:38) ~[na:na]
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:36) ~[na:na]
	at sbt.inc.Incremental$.cycle(Incremental.scala:73) ~[na:na]
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:33) ~[na:na]
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:32) ~[na:na]
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:41) ~[na:na]
	at sbt.inc.Incremental$.compile(Incremental.scala:32) ~[na:na]
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:26) ~[na:na]
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:150) ~[na:na]
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70) ~[na:na]
	at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45) ~[na:na]
	at sbt.Compiler$.apply(Compiler.scala:70) ~[na:na]
	at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:722) ~[na:na]
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716) ~[na:na]
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716) ~[na:na]
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47) ~[na:na]
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42) ~[na:na]
	at sbt.std.Transform$$anon$4.work(System.scala:64) ~[na:na]
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237) ~[na:na]
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237) ~[na:na]
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18) ~[na:na]
	at sbt.Execute.work(Execute.scala:244) ~[na:na]
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237) ~[na:na]
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237) ~[na:na]
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160) ~[na:na]
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30) ~[na:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_20]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_20]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_20]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]

2014-10-25 10:52:24,240 - [ERROR] - from application in New I/O worker #3 


! @6k1phoij3 - Internal server error, for (POST) [/answer] ->

play.PlayExceptions$UnexpectedException: Unexpected exception[The compilation failed without reporting any problem!]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$17.apply(PlayReloader.scala:306) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$17.apply(PlayReloader.scala:306) ~[na:na]
	at scala.Option.getOrElse(Option.scala:120) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:305) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[na:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]
sbt.compiler.CompileFailed: null
	at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:77) ~[na:na]
	at sbt.compiler.JavaTool$class.apply(JavaCompiler.scala:35) ~[na:na]
	at sbt.compiler.JavaCompiler$JavaTool0.apply(JavaCompiler.scala:63) ~[na:na]
	at sbt.compiler.JavaCompiler$class.compile(JavaCompiler.scala:21) ~[na:na]
	at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:63) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply$mcV$sp(AggressiveCompile.scala:126) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:126) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:126) ~[na:na]
	at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:159) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3.compileJava$1(AggressiveCompile.scala:125) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:142) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:86) ~[na:na]
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:38) ~[na:na]
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:36) ~[na:na]
	at sbt.inc.Incremental$.cycle(Incremental.scala:73) ~[na:na]
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:33) ~[na:na]
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:32) ~[na:na]
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:41) ~[na:na]
	at sbt.inc.Incremental$.compile(Incremental.scala:32) ~[na:na]
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:26) ~[na:na]
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:150) ~[na:na]
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70) ~[na:na]
	at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45) ~[na:na]
	at sbt.Compiler$.apply(Compiler.scala:70) ~[na:na]
	at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:722) ~[na:na]
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716) ~[na:na]
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716) ~[na:na]
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47) ~[na:na]
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42) ~[na:na]
	at sbt.std.Transform$$anon$4.work(System.scala:64) ~[na:na]
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237) ~[na:na]
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237) ~[na:na]
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18) ~[na:na]
	at sbt.Execute.work(Execute.scala:244) ~[na:na]
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237) ~[na:na]
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237) ~[na:na]
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160) ~[na:na]
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30) ~[na:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_20]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_20]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_20]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]

2014-10-25 10:52:34,556 - [ERROR] - from application in New I/O worker #3 


! @6k1php7po - Internal server error, for (GET) [/restaurant/1] ->

play.PlayExceptions$UnexpectedException: Unexpected exception[The compilation failed without reporting any problem!]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$17.apply(PlayReloader.scala:306) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$17.apply(PlayReloader.scala:306) ~[na:na]
	at scala.Option.getOrElse(Option.scala:120) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:305) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:298) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:296) ~[na:na]
	at scala.util.Either$LeftProjection.map(Either.scala:377) ~[na:na]
	at play.PlayReloader$$anon$1.reload(PlayReloader.scala:296) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:104) ~[na:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:102) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[na:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[na:na]
	at com.typesafe.trace.FutureRunnable.run(FutureTrace.scala:119) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[na:na]
sbt.compiler.CompileFailed: null
	at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:77) ~[na:na]
	at sbt.compiler.JavaTool$class.apply(JavaCompiler.scala:35) ~[na:na]
	at sbt.compiler.JavaCompiler$JavaTool0.apply(JavaCompiler.scala:63) ~[na:na]
	at sbt.compiler.JavaCompiler$class.compile(JavaCompiler.scala:21) ~[na:na]
	at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:63) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply$mcV$sp(AggressiveCompile.scala:126) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:126) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:126) ~[na:na]
	at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:159) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3.compileJava$1(AggressiveCompile.scala:125) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:142) ~[na:na]
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:86) ~[na:na]
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:38) ~[na:na]
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:36) ~[na:na]
	at sbt.inc.Incremental$.cycle(Incremental.scala:73) ~[na:na]
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:33) ~[na:na]
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:32) ~[na:na]
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:41) ~[na:na]
	at sbt.inc.Incremental$.compile(Incremental.scala:32) ~[na:na]
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:26) ~[na:na]
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:150) ~[na:na]
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70) ~[na:na]
	at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45) ~[na:na]
	at sbt.Compiler$.apply(Compiler.scala:70) ~[na:na]
	at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:722) ~[na:na]
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716) ~[na:na]
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716) ~[na:na]
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47) ~[na:na]
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42) ~[na:na]
	at sbt.std.Transform$$anon$4.work(System.scala:64) ~[na:na]
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237) ~[na:na]
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237) ~[na:na]
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18) ~[na:na]
	at sbt.Execute.work(Execute.scala:244) ~[na:na]
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237) ~[na:na]
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237) ~[na:na]
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160) ~[na:na]
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30) ~[na:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_20]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_20]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_20]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]

2014-10-25 10:53:17,139 - [INFO] - from play in play-internal-execution-context-41 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:53:17,166 - [INFO] - from play in play-internal-execution-context-41 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:53:17,240 - [INFO] - from play in play-internal-execution-context-41 
Application started (Dev)

2014-10-25 10:54:14,719 - [INFO] - from play in play-internal-execution-context-41 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:54:14,750 - [INFO] - from play in play-internal-execution-context-41 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:54:14,818 - [INFO] - from play in play-internal-execution-context-41 
Application started (Dev)

2014-10-25 10:54:40,873 - [INFO] - from play in play-internal-execution-context-41 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:54:40,897 - [INFO] - from play in play-internal-execution-context-41 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:54:40,963 - [INFO] - from play in play-internal-execution-context-41 
Application started (Dev)

2014-10-25 10:55:17,826 - [INFO] - from play in play-internal-execution-context-41 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:55:17,865 - [INFO] - from play in play-internal-execution-context-41 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:55:17,927 - [INFO] - from play in play-internal-execution-context-41 
Application started (Dev)

2014-10-25 10:55:18,080 - [ERROR] - from play in play-internal-execution-context-41 
Cannot invoke the action, eventually got an error: java.lang.StringIndexOutOfBoundsException: String index out of range: -1

2014-10-25 10:55:18,083 - [ERROR] - from application in play-internal-execution-context-41 


! @6k1pi8fng - Internal server error, for (POST) [/answer] ->

play.api.Application$$anon$1: Execution exception[[StringIndexOutOfBoundsException: String index out of range: -1]]
	at play.api.Application$class.handleError(Application.scala:293) ~[na:na]
	at play.api.DefaultApplication.handleError(Application.scala:399) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at scala.Option.map(Option.scala:145) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [na:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:260) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [na:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody0(Execution.scala:43) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute_aroundBody1$advice(Execution.scala:138) [na:na]
	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:1) [na:na]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete_aroundBody2(Promise.scala:248) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise$AjcClosure3.run(Promise.scala:1) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0proceed(FutureTraceAspect.aj:148) [na:na]
	at com.typesafe.trace.FutureTraceAspect.ajc$around$com_typesafe_trace_FutureTraceAspect$4$3fd2d6f0(FutureTraceAspect.aj:150) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [na:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [na:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [na:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1954) ~[na:1.8.0_20]
	at controllers.Search.AnswerQueryWithJson.searchPage(AnswerQueryWithJson.java:101) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$17$$anonfun$apply$17.apply(routes_routing.scala:265) ~[classes/:na]
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[na:na]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[na:na]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[na:na]
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[na:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:136) [na:na]
	at com.typesafe.trace.FutureCallback.apply(FutureTrace.scala:127) [na:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [na:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[na:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[na:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:385) ~[na:na]
	... 4 common frames omitted

2014-10-25 10:57:07,114 - [INFO] - from play in play-internal-execution-context-41 
datasource [jdbc:mysql://localhost/restaurantdb] bound to JNDI as DefaultDS

2014-10-25 10:57:07,141 - [INFO] - from play in play-internal-execution-context-41 
database [default] connected at jdbc:mysql://localhost/restaurantdb

2014-10-25 10:57:07,215 - [INFO] - from play in play-internal-execution-context-41 
Application started (Dev)

